# Generated by Django 5.1.6 on 2025-02-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='created_at',
        ),
    ]
